#! /bin/sh

if [ $# -eq 0 ]; then
    shutdown.exe -r -t 0
    echo "Rebooting now..."
    exit 1
fi

if [ ${1} -lt 0 ]; then
    shutdown.exe -a
    echo "Reboot canceled!"
else 
    mins=$((${1}*60))
    shutdown.exe -r -t $mins
    echo "Rebooting in ${1} minutes..."
fi